name: portfolio_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - plotly
  - pip
  - pip:
      - streamlit
      - yfinance
      - riskfolio-lib
